notifications:
  email: false
language: node_js
node_js:
- node
deploy:
  provider: npm
  email:
    secure: n2TpHMX1wO+V0ogB4nuc93knnuaEXaafLxLYxKgAplJ8ysgfWkukBU0zTqLswlv0ju4cRjjTR6FMn1T3KGTQw3bxcF97Akrj8XAb2YHx2b9AM09Jb3eyXTS2fNVcn/q0Eb2R3xom40gwMT7xxmnIEEQRr8oi4c30mh69+FVr54KRChzITk+z2TGKJ68b62SyOnXM+H8lXlzUl1LwTNb7jHR9xDIFe2q0pjzgxti0sGKNLeRcL48pJUjBgzPvnYrVuFQrtl7xTrBVUke5CCXyWb2gLsFsvGb1RnoaMwVvTqwG2Ri+bRzTxW38aHsb5MTCtai8Iul9lPABwmREXuMLcLdlq3Od8SMO02g4fhI8tOdREoL6VFJCHL+QBDdGrVg8N1YoLT1PWcvicimeUcCnOWaWpYHiPY1gcTaDV6GABkXGlodH1yhOEM5ay4N3t/nYooVB4x55632sGwmWTMNQ0ljII4PGrXeFowHVi6g8Z42Sa+8234uUsS5iDwdX9SiY31z/wQfxPVFAQwu4VxCGT5yIQDJW3rMkQ7Q0bWEPCYctC8OrPsY2oRWhgTmlQc4zSh1WUtjkBF+v2JTpveA5OiEoxfdlSdDdbzBJIEwJOkLHRJm2J/RaJm+SE7EWErHOB0XRWNmF0yWZg2yczAV09Tuzq05rztRA3/vQ8aURL7g=
  api_key:
    secure: hv014V2s7H12yjgkVzhU5eUHYncIxItQuRC2v2qpcyo2xxZhlXpfWI57eM3eHPd2QVBMfyGVSctGq5ny8mf+vBoFxHhTTaoG5A8b4jLBHv1Gtnk9JB6dtCflg4hm7fNXNO4Ma9fDCce0EHPWkhLBs/S12YxNlYzsZw72Q7cKsIzwzEoVbEh7JLjnSLZsy6aGvDgwT3kTgCX+1kPxs22hL4NdtJtgKg34TLI1EHVPc4zQ3e58Tzj5e6mkABUTBEaqiA/NW1Z1cSAbTSyBnk3IXDGoJJqdiDByc25URfu38Fnwu7eE3bo14rw/iiGWMOHq/5r6gWtJMUfiL6RVh+V5W1pjBwth20sBRmEw63gRovPOCbTvqbaeVI5+5xcVO2j3NMkKYF7gO3NO7fHmqR93gXSTkFhmZ+AJSj8Yy4GZODQnMBlifbQQeM6uspVqACASP6ym/WdkN1gxeQrLosYH2ICBKkNh02cwiZVyW4RsA3AEEAOZ9zYZ/mUYE5JtNQ6CHKZx4s4U3wqk/r9GQKExcN2Liynza+5Z87S6vfotGONnXZf1VbCvlXjB0CzZfSvr8w9EeYRqoqhmxlR8wStZg1H5KyB+KDqBiLHuztw6uT4QJ2k+iTghQ2Kf3Cy6WZYdOajDsOtc3FOhB0c0Iu1XnOIjhwa8M2epz/nckZ66LiM=
  on:
    tags: true
